version: 3

tasks:
  proto:
    cmds:
      - substreams protogen ./substreams.yaml --exclude-paths="sf/substreams,google"

  build:
    cmds:
      - cargo build --release --target wasm32-unknown-unknown

  run:
    cmds:
      - task: proto
      - task: build
      - substreams run -e mumbai.streamingfast.io:443 substreams.yaml map_events --start-block 35103633 --stop-block 35111602 -p map_deployments="registry_address=0x2b6bb12978a7d8b2b109cd41433bd8dc822d8b47" -p map_events="registry_address=0x2b6bb12978a7d8b2b109cd41433bd8dc822d8b47&split_main_address=0x2ed6c4b5da6378c7897ac67ba9e43102feb694ee&chain_id=80001"

  pack:
    cmds:
      - substreams pack ./substreams.yaml

  run:pack:
    cmds:
      - substreams run -e mumbai.streamingfast.io:443 masterfile-events-v0.1.0.spkg map_events --production-mode --start-block 35103633 --stop-block 37369482 -p map_deployments="registry_address=0x2b6bb12978a7d8b2b109cd41433bd8dc822d8b47" -p map_events="registry_address=0x2b6bb12978a7d8b2b109cd41433bd8dc822d8b47&split_main_address=0x2ed6c4b5da6378c7897ac67ba9e43102feb694ee&chain_id=80001"
