version: 3

tasks:
  proto:
    cmds:
      - substreams protogen ./substreams.yaml --exclude-paths="sf/substreams,google"

  build:
    cmds:
      - cargo build --release --target wasm32-unknown-unknown

  run:
    cmds:
      - task: proto
      - task: build
      - substreams run -e mumbai.streamingfast.io:443 substreams.yaml map_events --start-block 35103633 --stop-block 35104155 -p map_deployments=2b6bB12978a7d8b2b109cD41433bd8Dc822d8B47
